# Generated by Django 3.2.18 on 2023-04-05 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_alter_game_loc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(blank=True, max_length=100, null=True)),
                ('seller', models.CharField(max_length=100)),
                ('name', models.TextField()),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('link', models.URLField(unique=True)),
                ('lot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='lots.lot')),
            ],
        ),
    ]
