# Generated by Django 3.2.18 on 2023-04-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_rename_lot_id_item_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='online',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
