# Generated by Django 3.2.18 on 2023-04-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0006_followinglot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server', to='lots.game')),
            ],
        ),
    ]
