# Generated by Django 3.2.18 on 2023-04-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0007_serer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serer',
            new_name='Server',
        ),
    ]
