# Generated by Django 3.2.18 on 2023-04-11 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0009_alter_item_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='lots.server'),
        ),
    ]
