# Generated by Django 3.2.18 on 2023-04-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0011_followinglot_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='allow_monitoring',
            field=models.BooleanField(default=False),
        ),
    ]
