# Generated by Django 3.2.18 on 2023-04-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0012_lot_allow_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='followinglot',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
