# Generated by Django 3.2.18 on 2023-04-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0014_followinglot_monitoring_online_sellers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ('name',)},
        ),
    ]
