# Generated by Django 3.2.18 on 2023-04-13 08:49

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230412_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribe_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 11, 49, 2, 293635)),
        ),
    ]
